services:
  coreshop.sequence.generator:
    class: CoreShop\Component\Sequence\Generator\SequenceGenerator
    arguments: ['@coreshop.repository.sequence', '@coreshop.factory.sequence', '@doctrine.orm.entity_manager']