<?php 

/** 
* Generated at: 2017-10-19T10:40:44+03:00
* Inheritance: no
* Variants: no
* Changed by: system (0)


Fields Summary: 
- order [href]
- invoiceDate [date]
- invoiceNumber [input]
- totalNet [coreShopMoney]
- totalGross [coreShopMoney]
- totalTax [coreShopMoney]
- subtotalNet [coreShopMoney]
- subtotalGross [coreShopMoney]
- subtotalTax [coreShopMoney]
- shippingNet [coreShopMoney]
- shippingGross [coreShopMoney]
- shippingTax [coreShopMoney]
- shippingTaxRate [numeric]
- discountNet [coreShopMoney]
- discountGross [coreShopMoney]
- discountTax [coreShopMoney]
- paymentFeeNet [coreShopMoney]
- paymentFeeGross [coreShopMoney]
- paymentFeeTax [coreShopMoney]
- paymentFeeTaxRate [numeric]
- taxes [fieldcollections]
- baseTotalNet [coreShopMoney]
- baseTotalGross [coreShopMoney]
- baseTotalTax [coreShopMoney]
- baseSubtotalNet [coreShopMoney]
- baseSubtotalGross [coreShopMoney]
- baseSubtotalTax [coreShopMoney]
- baseShippingNet [coreShopMoney]
- baseShippingGross [coreShopMoney]
- baseShippingTax [coreShopMoney]
- baseDiscountNet [coreShopMoney]
- baseDiscountGross [coreShopMoney]
- baseDiscountTax [coreShopMoney]
- basePaymentFeeNet [coreShopMoney]
- basePaymentFeeGross [coreShopMoney]
- basePaymentFeeTax [coreShopMoney]
- baseTaxes [fieldcollections]
- items [multihref]
*/ 


return Pimcore\Model\DataObject\ClassDefinition::__set_state(array(
   'name' => 'CoreShopOrderInvoice',
   'description' => NULL,
   'creationDate' => NULL,
   'modificationDate' => 1508398842,
   'userOwner' => 0,
   'userModification' => 0,
   'parentClass' => 'CoreShop\\Component\\Order\\Model\\OrderInvoice',
   'useTraits' => NULL,
   'allowInherit' => false,
   'allowVariants' => false,
   'showVariants' => false,
   'layoutDefinitions' => 
  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
     'fieldtype' => 'panel',
     'labelWidth' => 100,
     'layout' => NULL,
     'name' => 'pimcore_root',
     'type' => NULL,
     'region' => NULL,
     'title' => NULL,
     'width' => NULL,
     'height' => NULL,
     'collapsible' => false,
     'collapsed' => NULL,
     'bodyStyle' => NULL,
     'datatype' => 'layout',
     'permissions' => NULL,
     'childs' => 
    array (
      0 => 
      Pimcore\Model\DataObject\ClassDefinition\Layout\Tabpanel::__set_state(array(
         'fieldtype' => 'tabpanel',
         'name' => 'Layout',
         'type' => NULL,
         'region' => NULL,
         'title' => NULL,
         'width' => NULL,
         'height' => NULL,
         'collapsible' => false,
         'collapsed' => NULL,
         'bodyStyle' => NULL,
         'datatype' => 'layout',
         'permissions' => NULL,
         'childs' => 
        array (
          0 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'labelWidth' => 100,
             'layout' => NULL,
             'name' => 'Invoice',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Invoice',
             'width' => NULL,
             'height' => NULL,
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Href::__set_state(array(
                 'fieldtype' => 'href',
                 'width' => '',
                 'assetUploadPath' => '',
                 'relationType' => true,
                 'queryColumnType' => 
                array (
                  'id' => 'int(11)',
                  'type' => 'enum(\'document\',\'asset\',\'object\')',
                ),
                 'phpdocType' => '\\Pimcore\\Model\\Document\\Page | \\Pimcore\\Model\\Document\\Snippet | \\Pimcore\\Model\\Document | \\Pimcore\\Model\\Asset | \\Pimcore\\Model\\DataObject\\AbstractObject',
                 'objectsAllowed' => true,
                 'assetsAllowed' => false,
                 'assetTypes' => 
                array (
                ),
                 'documentsAllowed' => false,
                 'documentTypes' => 
                array (
                ),
                 'lazyLoading' => true,
                 'classes' => 
                array (
                  0 => 
                  array (
                    'classes' => 'CoreShopOrder',
                  ),
                ),
                 'pathFormatterClass' => '',
                 'name' => 'order',
                 'title' => 'Order',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => true,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'columnType' => NULL,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
              )),
              1 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Date::__set_state(array(
                 'fieldtype' => 'date',
                 'queryColumnType' => 'bigint(20)',
                 'columnType' => 'bigint(20)',
                 'phpdocType' => '\\Carbon\\Carbon',
                 'defaultValue' => NULL,
                 'useCurrentDate' => false,
                 'name' => 'invoiceDate',
                 'title' => 'Invoice Date',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => true,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
              )),
              2 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Input::__set_state(array(
                 'fieldtype' => 'input',
                 'width' => NULL,
                 'queryColumnType' => 'varchar',
                 'columnType' => 'varchar',
                 'columnLength' => 190,
                 'phpdocType' => 'string',
                 'regex' => '',
                 'unique' => NULL,
                 'name' => 'invoiceNumber',
                 'title' => 'Invoice Number',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => true,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'relationType' => false,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
              )),
            ),
             'locked' => false,
          )),
          1 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'labelWidth' => 100,
             'layout' => NULL,
             'name' => 'Numbers',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Numbers',
             'width' => NULL,
             'height' => NULL,
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Layout\Tabpanel::__set_state(array(
                 'fieldtype' => 'tabpanel',
                 'name' => 'Layout',
                 'type' => NULL,
                 'region' => NULL,
                 'title' => NULL,
                 'width' => NULL,
                 'height' => NULL,
                 'collapsible' => false,
                 'collapsed' => NULL,
                 'bodyStyle' => NULL,
                 'datatype' => 'layout',
                 'permissions' => NULL,
                 'childs' => 
                array (
                  0 => 
                  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
                     'fieldtype' => 'panel',
                     'labelWidth' => 100,
                     'layout' => NULL,
                     'name' => 'Numbers (Converted)',
                     'type' => NULL,
                     'region' => NULL,
                     'title' => 'Numbers (Converted)',
                     'width' => NULL,
                     'height' => NULL,
                     'collapsible' => false,
                     'collapsed' => false,
                     'bodyStyle' => '',
                     'datatype' => 'layout',
                     'permissions' => NULL,
                     'childs' => 
                    array (
                      0 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'totalNet',
                         'title' => 'Total Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      1 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'totalGross',
                         'title' => 'Total Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      2 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'totalTax',
                         'title' => 'Total Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      3 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'subtotalNet',
                         'title' => 'Subtotal Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      4 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'subtotalGross',
                         'title' => 'Subtotal Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      5 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'subtotalTax',
                         'title' => 'Subtotal Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      6 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'shippingNet',
                         'title' => 'Shipping Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      7 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'shippingGross',
                         'title' => 'Shipping Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      8 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'shippingTax',
                         'title' => 'Shipping Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      9 => 
                      Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state(array(
                         'fieldtype' => 'numeric',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'double',
                         'columnType' => 'double',
                         'phpdocType' => 'float',
                         'integer' => false,
                         'unsigned' => false,
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'unique' => NULL,
                         'decimalSize' => NULL,
                         'decimalPrecision' => NULL,
                         'name' => 'shippingTaxRate',
                         'title' => 'Shipping Tax Rate',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      10 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'discountNet',
                         'title' => 'Discount Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      11 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'discountGross',
                         'title' => 'Discount Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      12 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'bigint(20)',
                         'columnType' => 'bigint(20)',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'discountTax',
                         'title' => 'Discount Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      13 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'paymentFeeNet',
                         'title' => 'Payment Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      14 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'paymentFeeGross',
                         'title' => 'Payment Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      15 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'paymentFeeTax',
                         'title' => 'Payment Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      16 => 
                      Pimcore\Model\DataObject\ClassDefinition\Data\Numeric::__set_state(array(
                         'fieldtype' => 'numeric',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'double',
                         'columnType' => 'double',
                         'phpdocType' => 'float',
                         'integer' => false,
                         'unsigned' => false,
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'unique' => NULL,
                         'decimalSize' => NULL,
                         'decimalPrecision' => NULL,
                         'name' => 'paymentFeeTaxRate',
                         'title' => 'Payment Tax Rate',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      17 => 
                      Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections::__set_state(array(
                         'fieldtype' => 'fieldcollections',
                         'phpdocType' => '\\Pimcore\\Model\\DataObject\\Fieldcollection',
                         'allowedTypes' => 
                        array (
                          0 => 'CoreShopTaxItem',
                        ),
                         'lazyLoading' => true,
                         'maxItems' => '',
                         'disallowAddRemove' => false,
                         'disallowReorder' => false,
                         'collapsed' => false,
                         'collapsible' => false,
                         'name' => 'taxes',
                         'title' => 'Taxes',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => false,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'columnType' => NULL,
                         'queryColumnType' => NULL,
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                    ),
                     'locked' => false,
                  )),
                  1 => 
                  Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
                     'fieldtype' => 'panel',
                     'labelWidth' => 100,
                     'layout' => NULL,
                     'name' => 'Numbers (Base)',
                     'type' => NULL,
                     'region' => NULL,
                     'title' => 'Numbers (Base)',
                     'width' => NULL,
                     'height' => NULL,
                     'collapsible' => false,
                     'collapsed' => false,
                     'bodyStyle' => '',
                     'datatype' => 'layout',
                     'permissions' => NULL,
                     'childs' => 
                    array (
                      0 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseTotalNet',
                         'title' => 'Base Total Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      1 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseTotalGross',
                         'title' => 'Base Total Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      2 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseTotalTax',
                         'title' => 'Base Total Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      3 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseSubtotalNet',
                         'title' => 'Base Subtotal Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      4 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseSubtotalGross',
                         'title' => 'Base Subtotal Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      5 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseSubtotalTax',
                         'title' => 'Base Subtotal Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      6 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseShippingNet',
                         'title' => 'Base Shipping Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      7 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseShippingGross',
                         'title' => 'Base Shipping Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      8 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseShippingTax',
                         'title' => 'Base Shipping Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      9 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseDiscountNet',
                         'title' => 'Discount Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      10 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseDiscountGross',
                         'title' => 'Discount Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      11 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'bigint(20)',
                         'columnType' => 'bigint(20)',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'baseDiscountTax',
                         'title' => 'Base Discount Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      12 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'basePaymentFeeNet',
                         'title' => 'Payment Net',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      13 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'basePaymentFeeGross',
                         'title' => 'Payment Gross',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      14 => 
                      CoreShop\Bundle\MoneyBundle\CoreExtension\Money::__set_state(array(
                         'fieldtype' => 'coreShopMoney',
                         'width' => '',
                         'defaultValue' => NULL,
                         'queryColumnType' => 'int',
                         'columnType' => 'int',
                         'phpdocType' => 'int',
                         'minValue' => NULL,
                         'maxValue' => NULL,
                         'name' => 'basePaymentFeeTax',
                         'title' => 'Base Payment Tax',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => true,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                      15 => 
                      Pimcore\Model\DataObject\ClassDefinition\Data\Fieldcollections::__set_state(array(
                         'fieldtype' => 'fieldcollections',
                         'phpdocType' => '\\Pimcore\\Model\\DataObject\\Fieldcollection',
                         'allowedTypes' => 
                        array (
                          0 => 'CoreShopTaxItem',
                        ),
                         'lazyLoading' => true,
                         'maxItems' => '',
                         'disallowAddRemove' => false,
                         'disallowReorder' => false,
                         'collapsed' => false,
                         'collapsible' => false,
                         'name' => 'baseTaxes',
                         'title' => 'Base Taxes',
                         'tooltip' => '',
                         'mandatory' => false,
                         'noteditable' => false,
                         'index' => false,
                         'locked' => false,
                         'style' => '',
                         'permissions' => NULL,
                         'datatype' => 'data',
                         'columnType' => NULL,
                         'queryColumnType' => NULL,
                         'relationType' => false,
                         'invisible' => false,
                         'visibleGridView' => false,
                         'visibleSearch' => false,
                      )),
                    ),
                     'locked' => false,
                  )),
                ),
                 'locked' => false,
              )),
            ),
             'locked' => false,
          )),
          2 => 
          Pimcore\Model\DataObject\ClassDefinition\Layout\Panel::__set_state(array(
             'fieldtype' => 'panel',
             'labelWidth' => 100,
             'layout' => NULL,
             'name' => 'Items',
             'type' => NULL,
             'region' => NULL,
             'title' => 'Items',
             'width' => NULL,
             'height' => NULL,
             'collapsible' => false,
             'collapsed' => false,
             'bodyStyle' => '',
             'datatype' => 'layout',
             'permissions' => NULL,
             'childs' => 
            array (
              0 => 
              Pimcore\Model\DataObject\ClassDefinition\Data\Multihref::__set_state(array(
                 'fieldtype' => 'multihref',
                 'width' => '',
                 'height' => '',
                 'maxItems' => '',
                 'assetUploadPath' => '',
                 'queryColumnType' => 'text',
                 'phpdocType' => 'array',
                 'relationType' => true,
                 'objectsAllowed' => true,
                 'assetsAllowed' => false,
                 'assetTypes' => 
                array (
                ),
                 'documentsAllowed' => false,
                 'documentTypes' => 
                array (
                ),
                 'lazyLoading' => true,
                 'classes' => 
                array (
                  0 => 
                  array (
                    'classes' => 'CoreShopOrderInvoiceItem',
                  ),
                ),
                 'pathFormatterClass' => '',
                 'name' => 'items',
                 'title' => 'Items',
                 'tooltip' => '',
                 'mandatory' => false,
                 'noteditable' => true,
                 'index' => false,
                 'locked' => false,
                 'style' => '',
                 'permissions' => NULL,
                 'datatype' => 'data',
                 'columnType' => NULL,
                 'invisible' => false,
                 'visibleGridView' => false,
                 'visibleSearch' => false,
              )),
            ),
             'locked' => false,
          )),
        ),
         'locked' => false,
      )),
    ),
     'locked' => false,
  )),
   'icon' => NULL,
   'previewUrl' => NULL,
   'group' => NULL,
   'showAppLoggerTab' => NULL,
   'linkGeneratorReference' => NULL,
   'propertyVisibility' => 
  array (
    'grid' => 
    array (
      'id' => true,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
    'search' => 
    array (
      'id' => true,
      'path' => true,
      'published' => true,
      'modificationDate' => true,
      'creationDate' => true,
    ),
  ),
   'dao' => NULL,
));
