CoreShop\Component\Index\Model\IndexColumn:
  type: mappedSuperclass
  table: coreshop_index_column
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    objectKey:
      column: objectKey
      type: string
      nullable: true
    objectType:
      column: objectType
      type: string
      nullable: false
    dataType:
      column: dataType
      type: string
      nullable: false
    name:
      column: name
      type: string
      nullable: false
    getter:
      column: getter
      type: string
      nullable: true
    getterConfig:
      column: getterConfig
      type: array
      nullable: true
    interpreter:
      column: interpreter
      type: string
      nullable: true
    interpreterConfig:
      column: interpreterConfig
      type: array
      nullable: true
    columnType:
      column: columnType
      type: string
    configuration:
      column: configuration
      type: array
      nullable: true
    creationDate:
      type: datetime
      gedmo:
        timestampable:
          on: create
    modificationDate:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    index:
      targetEntity: CoreShop\Component\Index\Model\IndexInterface
      inversedBy: columns
      joinColumn:
        name: indexId
        referencedColumnName: id
        nullable: true