CoreShop\Component\Taxation\Model\TaxRule:
  type: mappedSuperclass
  table: coreshop_tax_rule
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    behavior:
      type: integer
      column: behavior
    creationDate:
      type: datetime
      gedmo:
        timestampable:
          on: create
    modificationDate:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    taxRuleGroup:
      targetEntity: CoreShop\Component\Taxation\Model\TaxRuleGroupInterface
      inversedBy: taxRules
      joinColumn:
        name: taxRuleGroupId
        referencedColumnName: id
        nullable: false
    taxRate:
      targetEntity: CoreShop\Component\Taxation\Model\TaxRateInterface
      joinColumn:
        name: taxRateId
        referencedColumnName: id
        nullable: false
        onDelete: cascade