jms_serializer:
    metadata:
        directories:
            coreshop-order:
                namespace_prefix: "CoreShop\\Component\\Order"
                path: "@CoreShopOrderBundle/Resources/config/serializer"