CoreShop\Bundle\PayumBundle\Model\PaymentSecurityToken:
  type: mappedSuperclass
  table: coreshop_payment_security_token
  fields:
    hash:
      type: string
      column: hash
      id: true
      length: 100
    details:
      column: details
      type: object
      nullable: true
    afterUrl:
      column: afterUrl
      type: text
      nullable: true
    targetUrl:
      column: targetUrl
      type: text
      nullable: false
    gatewayName:
      column: gatewayName
      type: string
      length: 255
      nullable: false