parameters:
  coreshop.form.type.notification_rule.validation_groups: [coreshop]
  coreshop.form.type.notification_rule_group.validation_groups: [coreshop]
  coreshop.form.type.notification_rule.rule.validation_groups: [coreshop]
  coreshop.form.type.notification_rule.rule_action.validation_groups: [coreshop]
  coreshop.form.type.notification_rule.rule_condition.validation_groups: [coreshop]

services:
  coreshop.form.type.notification_rule:
    class: CoreShop\Bundle\NotificationBundle\Form\Type\NotificationRuleType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.model.notification_rule.class%', '%coreshop.form.type.notification_rule.validation_groups%']

  coreshop.form.type.notification_rule.rule_action:
    class: CoreShop\Bundle\NotificationBundle\Form\Type\NotificationRuleActionType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.model.rule_action.class%', '%coreshop.form.type.notification_rule.rule_action.validation_groups%', '@coreshop.form_registry.notification_rule.actions']

  coreshop.form.notification_rule.type.rule_action.collection:
    class: CoreShop\Bundle\NotificationBundle\Form\Type\NotificationRuleActionCollectionType
    tags:
        - { name: form.type }
    arguments: ['@coreshop.registry.notification_rule.actions']

  coreshop.form.notification_rule.type.rule_condition.collection:
    class: CoreShop\Bundle\NotificationBundle\Form\Type\NotificationRuleConditionCollectionType
    tags:
        - { name: form.type }
    arguments: ['@coreshop.registry.notification_rule.conditions']

  coreshop.form.notification_rule.type.rule_action_choice:
    class: CoreShop\Bundle\NotificationBundle\Form\Type\NotificationRuleActionChoiceType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.notification_rule.actions%']

  coreshop.form.notification_rule.type.rule_condition:
    class: CoreShop\Bundle\NotificationBundle\Form\Type\NotificationRuleConditionType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.model.rule_condition.class%', '%coreshop.form.type.notification_rule.rule_condition.validation_groups%', '@coreshop.form_registry.notification_rule.conditions']

  coreshop.form.notification_rule.type.rule_condition_choice:
    class: CoreShop\Bundle\NotificationBundle\Form\Type\NotificationRuleConditionChoiceType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.notification_rule.conditions%']

  coreshop.form.notification_rule_type.type_choice:
    class: CoreShop\Bundle\NotificationBundle\Form\Type\NotificationRuleTypeChoiceType
    arguments: ['%coreshop.notification_rule.actions.types%']
    tags:
      - { name: form.type }