services:
  coreshop.cart_price_rule.condition.products:
    class: CoreShop\Bundle\CoreBundle\Cart\Rule\Condition\ProductsConditionChecker
    tags:
      - { name: coreshop.cart_price_rule.condition, type: products, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\ProductsConfigurationType }

  coreshop.cart_price_rule.condition.categories:
    class: CoreShop\Bundle\CoreBundle\Cart\Rule\Condition\CategoriesConditionChecker
    tags:
      - { name: coreshop.cart_price_rule.condition, type: categories, form-type: CoreShop\Bundle\CoreBundle\Form\Type\Rule\Condition\CategoriesConfigurationType }

