services:
    coreshop.admin_controller.settings:
      class: CoreShop\Bundle\CoreBundle\Controller\SettingsController
      calls:
        - [setContainer, ['@service_container']]

    coreshop.admin_controller.reports:
      class: CoreShop\Bundle\CoreBundle\Controller\ReportsController
      calls:
        - [setContainer, ['@service_container']]
