CoreShop\Component\Rule\Model\Condition:
  type: mappedSuperclass
  table: coreshop_rule_condition
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    type:
      column: type
      type: string
    configuration:
      column: configuration
      type: array
      nullable: true