services:
  coreshop.routing.route.factory:
    class: CoreShop\Bundle\ResourceBundle\Routing\RouteFactory
    public: false

  coreshop.routing.loader.resource:
    class: CoreShop\Bundle\ResourceBundle\Routing\ResourceLoader
    public: false
    arguments: ['@coreshop.resource_registry', '@coreshop.routing.route.factory']
    tags:
      - { name: routing.loader }