CoreShop\Component\Core\Model\Carrier:
  exclusion_policy: ALL
  xml_root_name: carrier
  properties:
    taxRule:
      expose: true
      type: relation
      groups: [Detailed]
    stores:
      expose: true
      type: relation
      groups: [Detailed]