services:
  coreshop.payum_extension.update_payment_state:
    class: CoreShop\Bundle\PayumBundle\Extension\UpdatePaymentStateExtension
    arguments: ['@doctrine.orm.entity_manager']
    tags:
        - { name: payum.extension, all: true, prepend: true }

  coreshop.payum_extension.update_order_workflow_extension:
    class: CoreShop\Bundle\PayumBundle\Extension\UpdateOrderWorkflowExtension
    arguments: ['@coreshop.repository.order', '@coreshop.workflow.manager.order']
    tags:
        - { name: payum.extension, all: true, prepend: true }