parameters:
  coreshop.form.type.gateway_config.validation_groups: [coreshop]

services:
  coreshop.form.type.gateway.config:
    class: CoreShop\Bundle\PayumBundle\Form\Type\GatewayConfigType
    arguments:
      - '%coreshop.model.gateway_config.class%'
      - '%coreshop.form.type.gateway_config.validation_groups%'
      - '@coreshop.form_registry.payum_gateway_config'
    tags:
      - { name: form.type }

  coreshop.form.type.gateway_configuration.paypal:
    class: CoreShop\Bundle\PayumBundle\Form\Type\PaypalGatewayConfigurationType
    tags:
      - { name: coreshop.gateway_configuration_type, type: paypal_express_checkout }
      - { name: form.type }

  coreshop.form.type.gateway_configuration.sofort:
    class: CoreShop\Bundle\PayumBundle\Form\Type\SofortGatewayConfigurationType
    tags:
      - { name: coreshop.gateway_configuration_type, type: sofort }
      - { name: form.type }