imports:
  - { resource: "services/form.yml" }
  - { resource: "services/shipping-rules.yml" }

services:
  # Carrier Validator
  coreshop.shipping.carrier.validator.composite:
    class: CoreShop\Bundle\ShippingBundle\Validator\CompositeShippableCarrierValidator
    public: false

  # Carrier Processor
  coreshop.carrier.discovery:
    class: CoreShop\Bundle\ShippingBundle\Discover\ShippableCarriersDiscovery
    arguments: ['@coreshop.repository.carrier', '@coreshop.shipping.carrier.validator']

  # Carrier Price Calculator
  coreshop.registry.shipping.price_calculators:
    class: CoreShop\Component\Registry\PrioritizedServiceRegistry
    arguments:
      - CoreShop\Component\Shipping\Calculator\CarrierPriceCalculatorInterface
      - shipping-price-calculators

  coreshop.carrier.price_calculator:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CarrierPriceCalculator
    arguments: ['@coreshop.registry.shipping.price_calculators']

  coreshop.carrier.price_calculator.shipping_rules:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CarrierShippingRulePriceCalculator
    arguments:
      - '@coreshop.carrier.shipping_rule.checker'
      - '@coreshop.carrier.processor.shipping_rules'
    tags:
      - { name: coreshop.shipping.price_calculator, type: shipping-rule, priority: 256 }

  coreshop.carrier.price_calculator.default:
    class: CoreShop\Bundle\ShippingBundle\Calculator\CompositePriceCalculator
    arguments: [['@coreshop.carrier.price_calculator']]
