CoreShop\Component\Shipping\Model\ShippingRule:
  type: mappedSuperclass
  table: coreshop_shipping_rule
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    name:
      column: name
      type: string
    creationDate:
      type: datetime
      gedmo:
        timestampable:
          on: create
    modificationDate:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToMany:
    conditions:
      targetEntity: CoreShop\Component\Rule\Model\ConditionInterface
      cascade:
        - all
      joinTable:
        name: coreshop_shipping_rule_conditions
        joinColumns:
          shipping_rule_id:
            referencedColumnName: id
            nullable: false
            onDelete: cascade
        inverseJoinColumns:
          condition_id:
            referencedColumnName: id
            nullable: false
            onDelete: cascade

    actions:
      targetEntity: CoreShop\Component\Rule\Model\ActionInterface
      cascade:
        - all
      joinTable:
        name: coreshop_shipping_rule_actions
        joinColumns:
          shipping_rule_id:
            referencedColumnName: id
            nullable: false
            onDelete: cascade
        inverseJoinColumns:
          action_id:
            referencedColumnName: id
            nullable: false
            onDelete: cascade