pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopCarrier: CoreShop\Bundle\ShippingBundle\CoreExtension\Carrier
                    coreShopCarrierMultiselect: CoreShop\Bundle\ShippingBundle\CoreExtension\CarrierMultiselect
