CoreShop\Component\Index\Model\Filter:
  properties:
    name:
      - NotBlank: { groups: [coreshop] }
    resultsPerPage:
      - Type:
          type: integer
          groups: [coreshop]
    orderDirection:
      - Type:
          type: string
          groups: [coreshop]
    orderKey:
      - Type:
          type: string
          groups: [coreshop]
    index:
      - NotBlank: { groups: [coreshop] }