CoreShop\Component\Index\Model\FilterCondition:
  properties:
    type:
      - NotBlank: { groups: [coreshop] }
    field:
      - NotBlank: { groups: [coreshop] }
    label:
      - NotBlank: { groups: [coreshop] }