CoreShop\Component\Index\Model\Index:
  properties:
    name:
      - NotBlank: { groups: [coreshop] }
    class:
      - NotBlank: { groups: [coreshop] }
    worker:
      - NotBlank: { groups: [coreshop] }