services:
  coreshop.store_collector:
    class: CoreShop\Bundle\StoreBundle\Collector\StoreCollector
    arguments: ['@coreshop.repository.store', '@coreshop.context.store', false]
    tags:
      - { name: data_collector, template: 'CoreShopStoreBundle:Collector:store.html.twig', id: coreshop.store_collector}