CoreShop\Component\Store\Model\Store:
  type: mappedSuperclass
  table: coreshop_store
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      column: name
    template:
      type: string
      column: template
    isDefault:
      column: isDefault
      type: boolean
    siteId:
      column: siteId
      type: integer
    creationDate:
      type: datetime
      gedmo:
        timestampable:
          on: create
    modificationDate:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    currency:
      targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
      joinColumn:
        name: currencyId
        referencedColumnName: id
        nullable: true
