parameters:
  coreshop.form.type.index.validation_groups: [coreshop]
  coreshop.form.type.index.column.validation_groups: [coreshop]
  coreshop.form.type.index.column_type.validation_groups: [coreshop]
  coreshop.form.type.index.columns.validation_groups: [coreshop]
  coreshop.form.type.index.worker.validation_groups: [coreshop]
  coreshop.form.type.filter.validation_groups: [coreshop]
  coreshop.form.type.filter.filter_condition.validation_groups: [coreshop]

services:
  coreshop.form.type.index:
    class: CoreShop\Bundle\IndexBundle\Form\Type\IndexType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.model.index.class%', '%coreshop.form.type.index.validation_groups%', '@coreshop.form_registry.index.worker']

  coreshop.form.type.index_column:
    class: CoreShop\Bundle\IndexBundle\Form\Type\IndexColumnType
    tags:
        - { name: form.type }
    arguments:
      - '%coreshop.model.index_column.class%'
      - '%coreshop.form.type.index.column_type.validation_groups%'
      - '@coreshop.form_registry.index_column_types'
      - '@coreshop.form_registry.index.getter'
      - '@coreshop.form_registry.index.interpreter'

  coreshop.form.type.index.index_column_choice:
    class: CoreShop\Bundle\IndexBundle\Form\Type\IndexColumnChoiceType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.index.column_types%']

  coreshop.form.type.index_column.type_collection:
    class: CoreShop\Bundle\IndexBundle\Form\Type\IndexColumnCollectionType
    tags:
        - { name: form.type }
    arguments: ['@coreshop.registry.index.column_types']

  coreshop.form.type.index.worker_choice:
    class: CoreShop\Bundle\IndexBundle\Form\Type\IndexWorkerChoiceType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.index.workers%']

  coreshop.form.type.index.getter_choice:
    class: CoreShop\Bundle\IndexBundle\Form\Type\IndexColumnGetterChoiceType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.index.getters%']

  coreshop.form.type.index.interpter_choice:
    class: CoreShop\Bundle\IndexBundle\Form\Type\IndexColumnInterpreterChoiceType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.index.interpreters%']


  # Filter Forms
  coreshop.form.type.filter:
    class: CoreShop\Bundle\IndexBundle\Form\Type\FilterType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.model.filter.class%', '%coreshop.form.type.filter.validation_groups%']

  coreshop.form.type.filter.condition_type:
    class: CoreShop\Bundle\IndexBundle\Form\Type\FilterConditionType
    tags:
        - { name: form.type }
    arguments:
      - '%coreshop.model.filter_condition.class%'
      - '%coreshop.form.type.filter.filter_condition.validation_groups%'
      - '@coreshop.form_registry.filter.condition_types'

  coreshop.form.type.filter.condition_choice_type:
    class: CoreShop\Bundle\IndexBundle\Form\Type\FilterConditionChoiceType
    tags:
        - { name: form.type }
    arguments: ['%coreshop.filter.condition_types%']

  coreshop.form.type.filter.condition_type_collection:
    class: CoreShop\Bundle\IndexBundle\Form\Type\FilterConditionCollectionType
    tags:
        - { name: form.type }
    arguments: ['@coreshop.registry.filter.condition_types']

  coreshop.form.type.index_choice:
    class: CoreShop\Bundle\IndexBundle\Form\Type\IndexChoiceType
    arguments:
      - '@coreshop.repository.index'
    tags:
      -  { name: form.type }