services:
  ‌coreshop.listeners.index.post_save:
    class: CoreShop\Bundle\IndexBundle\EventListener\CreateIndexListener
    arguments:
      - '@coreshop.registry.index.worker'
    tags:
      - { name: kernel.event_listener, event: coreshop.index.post_save, method: onIndexSavePost }

  coreshop.listeners.index.object.post_update:
    class: CoreShop\Bundle\IndexBundle\EventListener\IndexObjectListener
    arguments:
      - '@coreshop.index.updater'
    tags:
      - { name: kernel.event_listener, event: pimcore.dataobject.postUpdate, method: onPostUpdate }