pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopStore: CoreShop\Bundle\StoreBundle\CoreExtension\Store
                    coreShopStoreMultiselect: CoreShop\Bundle\StoreBundle\CoreExtension\StoreMultiselect
