imports:
  - { resource: "services/form.yml" }

services:
  coreshop.configuration.service:
    class: CoreShop\Component\Configuration\Service\ConfigurationService
    arguments: ['@doctrine.orm.default_entity_manager', '@coreshop.repository.configuration', '@coreshop.factory.configuration']

  coreshop.jms_serializer.handler.object:
    class: CoreShop\Bundle\ConfigurationBundle\Serialization\ObjectHandler
    tags:
      - { name: jms_serializer.handler, type: object, direction: serialization, format: json, method: serializeRelation}