jms_serializer:
    metadata:
        directories:
            coreshop-store:
                namespace_prefix: "CoreShop\\Component\\Store"
                path: "@CoreShopStoreBundle/Resources/config/serializer"

liip_theme:
    load_controllers: false