# This file is basically a copy of Pimcore's .travis.yml
# Actually, very dangerous, cause it depends on Pimcore's travis configuration files
# Which could be removed at any time from them

notifications:
  email:
    - travis-ci@coreshop.org

sudo: false
language: php

php:
  - 7
  - 7.1

services:
  - redis

addons:
  mariadb: '10.1'
  hosts:
    - pimcore-test.dev

matrix:
  include:
    - os: linux
      sudo: required
      php: 7
    - os: linux
      sudo: required
      php: 7.1

env:
  global:
    - PIMCORE_ENVIRONMENT=test
    - CORESHOP_TEST=1
    - CORESHOP_MYSQL_HOST=127.0.0.1
    - CORESHOP_MYSQL_DB=coreshop_phpunit
    - CORESHOP_MYSQL_USER=root
cache:
    directories:
        - ~/.composer/cache/files
        - vendor

before_install:
 - mkdir $TRAVIS_BUILD_DIR/../lib
 - mkdir $TRAVIS_BUILD_DIR/../lib/CoreShop
 - mv $TRAVIS_BUILD_DIR/{.[!.],}* $TRAVIS_BUILD_DIR/../lib/CoreShop
 - rm -rf $TRAVIS_BUILD_DIR/{.[!.],}*
 - git clone https://github.com/pimcore/pimcore.git $TRAVIS_BUILD_DIR
 - phpenv config-add $TRAVIS_BUILD_DIR/../lib/CoreShop/.gitlab-ci/php.ini

install:
  # add config templates
  - mkdir -p var/config
  - cp .travis/system.template.php var/config/system.php
  - cp app/config/parameters.example.yml app/config/parameters.yml
  - composer install

  # Add path to CoreShop
  - composer config repositories.coreshop path $TRAVIS_BUILD_DIR/../lib/CoreShop

  - composer require doctrine/instantiator:1.0.5
  # Include CoreShop with specific commit to test it, because of Pimcore's way of dealing not as dependency,
  # this test is kinda stupid
  - composer require coreshop/core-shop dev-master#$TRAVIS_COMMIT --dev
  - composer require symfony/phpunit-bridge:^3.3
  - composer update

script:
  - vendor/bin/phpunit -c vendor/coreshop/core-shop/tests/config/ --bootstrap vendor/coreshop/core-shop/tests/bootstrap.php vendor/coreshop/core-shop/tests/AllTests
