imports:
  - { resource: "services/form.yml" }

services:
  coreshop.currency_converter:
    class: CoreShop\Component\Currency\Converter\CurrencyConverter
    arguments: ['@coreshop.repository.exchange_rate', '@coreshop.repository.currency']

  coreshop.templating.helper.currency:
    class: CoreShop\Bundle\CurrencyBundle\Templating\Helper\CurrencyHelper
    tags:
      - { name: templating.helper, alias: coreshop_currency }
    lazy: true

  coreshop.twig.extension.currency:
    class: CoreShop\Bundle\CurrencyBundle\Twig\CurrencyExtension
    public: false
    tags:
      - { name: twig.extension }
    arguments: ['@coreshop.templating.helper.currency']

  coreshop.context.currency.composite:
    class: CoreShop\Component\Currency\Context\CompositeCurrencyContext
    decorates: coreshop.context.currency
    decoration_priority: 256
    public: false

  coreshop.context.currency.cached:
    class: CoreShop\Component\Currency\Context\CachedCurrencyContext
    decorates: coreshop.context.currency
    decoration_priority: 255
    arguments:
      - '@coreshop.context.currency.cached.inner'

  coreshop.context.currency.fixed:
    class: CoreShop\Component\Currency\Context\FixedCurrencyContext
    tags:
      - { name: 'coreshop.context.currency' }