pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopCurrency: CoreShop\Bundle\CurrencyBundle\CoreExtension\Currency
                    coreShopCurrencyMultiselect: CoreShop\Bundle\CurrencyBundle\CoreExtension\CurrencyMultiselect
