imports:
  - { resource: "@CoreShopAddressBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopCurrencyBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopStoreBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopTaxationBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopProductBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopIndexBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopCustomerBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopShippingBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopPaymentBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopOrderBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopConfigurationBundle/Resources/config/app/config.yml" }
  - { resource: "@CoreShopNotificationBundle/Resources/config/app/config.yml" }

  - { resource: "@CoreShopCoreBundle/Resources/config/app/coreshop.yml" }
  - { resource: "@CoreShopCoreBundle/Resources/config/app/security.yml" }
  - { resource: "@CoreShopCoreBundle/Resources/config/app/payum.yml" }
  - { resource: "@CoreShopCoreBundle/Resources/config/app/checkout.yml" }

jms_serializer:
  metadata:
    directories:
      core-shop-core:
        namespace_prefix: "CoreShop\\Component\\Core"
        path: "@CoreShopCoreBundle/Resources/config/serializer"

twig:
  globals:
    coreshop: "@coreshop.context.shopper"
