imports:
  - { resource: "services/form.yml" }
  - { resource: "services/extension.yml" }

services:
  coreshop.form_registry.payum_gateway_config:
    class: CoreShop\Bundle\ResourceBundle\Form\Registry\FormTypeRegistry

  coreshop.payum.http_client:
    class: Payum\Core\HttpClientInterface
    factory: [Payum\Core\Bridge\Guzzle\HttpClientFactory, create]


  coreshop.payum_action.resolve_next_route:
    class: CoreShop\Bundle\PayumBundle\Action\ResolveNextRouteAction
    tags:
      - { name: payum.action, all: true, alias: coreshop.resolve_next_route }

  # Offline Payment
  coreshop.payum_action.offline.convert_payment:
    class: CoreShop\Bundle\PayumBundle\Action\Offline\ConvertPaymentAction
    tags:
      - { name: payum.action, factory: offline, alias: coreshop.offline.convert_payment }

  coreshop.payum_action.offine.resolve_next_route:
    class: CoreShop\Bundle\PayumBundle\Action\Offline\ResolveNextRouteAction
    tags:
      - { name: payum.action, factory: offline, alias: coreshop.offline.resolve_next_route }

  coreshop.payum_action.offline.status:
    class: CoreShop\Bundle\PayumBundle\Action\Offline\StatusAction
    tags:
      - { name: payum.action, factory: offline, alias: coreshop.offline.status }