CoreShop\Component\Core\Model\Configuration:
  type: mappedSuperclass
  table: coreshop_configuration
  manyToOne:
    store:
      targetEntity: CoreShop\Component\Store\Model\StoreInterface
      inversedBy: configurations
      joinColumn:
        name: store_id
        referencedColumnName: id
        nullable: true