CoreShop\Component\Core\Model\Country:
  type: mappedSuperclass
  table: coreshop_country
  manyToOne:
    currency:
      targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
      inversedBy: countries
      orphanRemoval: false
      joinColumn:
        name: currencyId
        referencedColumnName: id
        nullable: true
        cascade:
          - 'persist'
  manyToMany:
    stores:
      targetEntity: CoreShop\Component\Store\Model\StoreInterface
      inversedBy: countries
      joinTable:
        name: coreshop_country_stores
        joinColumns:
          country_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          store_id:
            referencedColumnName: id
            nullable: false
      cascade:
        - remove