CoreShop\Component\Core\Model\PaymentProvider:
  type: mappedSuperclass
  table: coreshop_payment_provider
  manyToMany:
    stores:
      targetEntity: CoreShop\Component\Store\Model\StoreInterface
      joinTable:
        name: coreshop_payment_provider_stores
        joinColumns:
          payment_method_id:
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE
        inverseJoinColumns:
          store_id:
            referencedColumnName: id
            nullable: false
            onDelete: CASCADE
  manyToOne:
    gatewayConfig:
      targetEntity: CoreShop\Bundle\PayumBundle\Model\GatewayConfig
      joinColumn:
        name: gateway_config_id
        referencedColumnName: id
        nullable: true
        onDelete: "SET NULL"
      cascade: [ persist ]