CoreShop\Component\Core\Model\Store:
  type: mappedSuperclass
  table: coreshop_store
  manyToOne:
    baseCountry:
      targetEntity: CoreShop\Component\Address\Model\CountryInterface
      joinColumn:
        name: baseCountryId
        referencedColumnName: id
        nullable: true
      fetch: EAGER
  oneToMany:
    configurations:
      targetEntity: CoreShop\Component\Configuration\Model\ConfigurationInterface
      orphanRemoval: true
      mappedBy: store
      cascade: [ persist, remove ]
      fetch: EAGER
  manyToMany:
    countries:
      targetEntity: CoreShop\Component\Address\Model\CountryInterface
      mappedBy: stores
      joinTable:
        name: coreshop_country_stores
        joinColumns:
          country_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          store_id:
            referencedColumnName: id
            nullable: false
      cascade:
        - remove
    taxRuleGroups:
      targetEntity: CoreShop\Component\Taxation\Model\TaxRuleGroupInterface
      mappedBy: stores
      joinTable:
        name: coreshop_tax_rule_group_stores
        joinColumns:
          store_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          tax_rule_group_id:
            referencedColumnName: id
            nullable: false
      cascade:
        - remove