CoreShop\Component\Core\Model\TaxRuleGroup:
  type: mappedSuperclass
  table: coreshop_tax_rule_group
  manyToMany:
    stores:
      targetEntity: CoreShop\Component\Store\Model\StoreInterface
      inversedBy: taxRuleGroups
      joinTable:
        name: coreshop_tax_rule_group_stores
        joinColumns:
          store_id:
            referencedColumnName: id
            nullable: false
        inverseJoinColumns:
          tax_rule_group_id:
            referencedColumnName: id
            nullable: false