CoreShop\Component\Currency\Model\Currency:
  type: mappedSuperclass
  table: coreshop_currency
  indexes:
    isoCode:
      columns: [ isoCode ]
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    isoCode:
      type: string
      column: isoCode
      length: 3
      nullable: true
    name:
      column: name
      type: string
    numericIsoCode:
      column: numericIsoCode
      type: integer
      nullable: true
    symbol:
      column: symbol
      type: string
      nullable: true
    creationDate:
      type: datetime
      gedmo:
        timestampable:
          on: create
    modificationDate:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update