CoreShop\Component\Currency\Model\ExchangeRate:
  type: mappedSuperclass
  table: coreshop_exchange_rate
  uniqueConstraints:
    currencies:
      columns: [fromCurrency, toCurrency]
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    exchangeRate:
      type: decimal
      column: exchangeRate
      precision: 10
      scale: 5
    creationDate:
      type: datetime
      gedmo:
        timestampable:
          on: create
    modificationDate:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update
  manyToOne:
    fromCurrency:
      targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
      joinColumn:
        name: fromCurrency
        referencedColumnName: id
        nullable: false
        onDelete: cascade
    toCurrency:
      targetEntity: CoreShop\Component\Currency\Model\CurrencyInterface
      joinColumn:
        name: toCurrency
        referencedColumnName: id
        nullable: false
        onDelete: cascade
