CoreShop\Component\Shipping\Model\ShippingRuleGroup:
  properties:
    carrier:
      - NotBlank: { groups: [coreshop] }
    priority:
      - NotBlank: { groups: [coreshop] }
      - Type:
          type: integer