CoreShop\Component\Payment\Model\PaymentProviderTranslation:
  type: mappedSuperclass
  table: coreshop_payment_provider_translation
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    name:
      type: string
      column: name
    description:
      type: text
      column: description
      nullable: true
    instructions:
      type: text
      column: instructions
      nullable: true
    creationDate:
      type: datetime
      gedmo:
        timestampable:
          on: create
    modificationDate:
      type: datetime
      nullable: true
      gedmo:
        timestampable:
          on: update