CoreShop\Component\Store\Model\Store:
  properties:
    name:
      - NotBlank: { groups: [coreshop] }
    currency:
      - NotBlank: { groups: [coreshop] }
    template:
      - NotBlank: { groups: [coreshop] }
    isDefault:
      - Type:
          type: boolean
          groups: [coreshop]
    siteId:
      - Type:
          type: integer
          groups: [coreshop]