CoreShop\Component\Sequence\Model\Sequence:
  type: mappedSuperclass
  table: coreshop_sequence
  fields:
    id:
      type: integer
      column: id
      id: true
      generator:
        strategy: AUTO
    type:
      column: name
      type: string
      unique: true
      length: 100
    index:
      column: idx
      type: integer
      nullable: false