coreshop_admin_cart_price_rule:
  type: coreshop.resources
  resource: |
    alias: coreshop.cart_price_rule
    additional_routes:
      config:
        path: get-config
        action: getConfig
        methods:
          - GET
      getVoucherCodes:
        path: get-voucher-codes
        action: getVoucherCodes
        methods:
          - GET
      generateVoucherCodes:
        path: generate-voucher-codes
        action: generateVoucherCodes
        methods:
          - POST
      exportVoucherCodes:
        path: export-voucher-codes
        action: exportVoucherCodes
        methods:
          - GET
          - POST

##### ORDERS
coreshop_order_get_grid_configuration:
  path: /%coreshop.admin.route.base%/order/get-grid-configuration
  defaults: { _controller: 'coreshop.pimcore_controller.order:getGridConfigurationAction'}

coreshop_order_get_states:
  path: /%coreshop.admin.route.base%/order/get-states
  defaults: { _controller: 'coreshop.pimcore_controller.order:getStatesAction'}

coreshop_order_get_orders:
  path: /%coreshop.admin.route.base%/order/list
  defaults: { _controller: 'coreshop.pimcore_controller.order:listAction'}

coreshop_order_get_order:
  path: /%coreshop.admin.route.base%/order/detail
  defaults: { _controller: 'coreshop.pimcore_controller.order:detailAction'}

coreshop_order_update_payment:
  path: /%coreshop.admin.route.base%/order/update-payment
  defaults: { _controller: 'coreshop.pimcore_controller.order:updatePaymentAction'}

coreshop_order_add_payment:
  path: /%coreshop.admin.route.base%/order/add-payment
  defaults: { _controller: 'coreshop.pimcore_controller.order:addPaymentAction'}

coreshop_order_find:
  path: /%coreshop.admin.route.base%/order/find
  defaults: { _controller: 'coreshop.pimcore_controller.order:findSaleAction'}

coreshop_order_get_payment_providers:
  path: /%coreshop.admin.route.base%/order/get-payment-providers
  defaults: { _controller: 'coreshop.pimcore_controller.order:getPaymentProvidersAction'}

##### ORDER INVOICE
coreshop_order_invoice_get_processable_items:
  path: /%coreshop.admin.route.base%/order-invoice/get-invoice-able-items
  defaults: { _controller: 'coreshop.pimcore_controller.order_invoice:getInvoiceAbleItemsAction'}

coreshop_order_invoice_create:
  path: /%coreshop.admin.route.base%/order-invoice/create-invoice
  defaults: { _controller: 'coreshop.pimcore_controller.order_invoice:createInvoiceAction'}

coreshop_order_invoice_render:
  path: /%coreshop.admin.route.base%/order-invoice/render
  defaults: { _controller: 'coreshop.pimcore_controller.order_invoice:renderAction'}

##### ORDER SHIPMENT
coreshop_order_shipment_get_processable_items:
  path: /%coreshop.admin.route.base%/order-shipment/get-ship-able-items
  defaults: { _controller: 'coreshop.pimcore_controller.order_shipment:getShipAbleItemsAction'}

coreshop_order_shipment_create:
  path: /%coreshop.admin.route.base%/order-shipment/create-shipment
  defaults: { _controller: 'coreshop.pimcore_controller.order_shipment:createShipmentAction'}

coreshop_order_shipment_render:
  path: /%coreshop.admin.route.base%/order-shipment/render
  defaults: { _controller: 'coreshop.pimcore_controller.order_shipment:renderAction'}

##### ORDER CREATION
coreshop_order_get_product_details:
  path: /%coreshop.admin.route.base%/order-creation/get-product-details
  defaults: { _controller: 'coreshop.pimcore_controller.order_creation:getProductDetailsAction'}

coreshop_order_get_customer_details:
  path: /%coreshop.admin.route.base%/order-creation/get-customer-details
  defaults: { _controller: 'coreshop.pimcore_controller.order_creation:getCustomerDetailsAction'}

coreshop_order_get_totals:
  path: /%coreshop.admin.route.base%/order-creation/get-totals
  defaults: { _controller: 'coreshop.pimcore_controller.order_creation:getTotalsAction'}

coreshop_order_create:
  path: /%coreshop.admin.route.base%/order-creation/create-sale
  defaults: { _controller: 'coreshop.pimcore_controller.order_creation:createSaleAction'}

##### QUOTES
coreshop_quote_get_grid_configuration:
  path: /%coreshop.admin.route.base%/quote/get-grid-configuration
  defaults: { _controller: 'coreshop.pimcore_controller.quote:getGridConfigurationAction'}

coreshop_quote_get_quotes:
  path: /%coreshop.admin.route.base%/quote/list
  defaults: { _controller: 'coreshop.pimcore_controller.quote:listAction'}

coreshop_quote_get_quote:
  path: /%coreshop.admin.route.base%/quote/detail
  defaults: { _controller: 'coreshop.pimcore_controller.quote:detailAction'}

coreshop_quote_find:
  path: /%coreshop.admin.route.base%/quote/find
  defaults: { _controller: 'coreshop.pimcore_controller.quote:findSaleAction'}

##### QUOTE CREATION
coreshop_quote_get_product_details:
  path: /%coreshop.admin.route.base%/quote-creation/get-product-details
  defaults: { _controller: 'coreshop.pimcore_controller.quote_creation:getProductDetailsAction'}

coreshop_quote_get_customer_details:
  path: /%coreshop.admin.route.base%/quote-creation/get-customer-details
  defaults: { _controller: 'coreshop.pimcore_controller.quote_creation:getCustomerDetailsAction'}

coreshop_quote_get_totals:
  path: /%coreshop.admin.route.base%/quote-creation/get-totals
  defaults: { _controller: 'coreshop.pimcore_controller.quote_creation:getTotalsAction'}

coreshop_quote_create:
  path: /%coreshop.admin.route.base%/quote-creation/create-sale
  defaults: { _controller: 'coreshop.pimcore_controller.quote_creation:createSaleAction'}